apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.a }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.b }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespaces.c }}