apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-ingress-by-default
  namespace: {{ .Values.namespaces.a }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress: []